# Generated by Django 4.2 on 2023-04-24 02:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.PositiveIntegerField()),
                ("product_name", models.CharField(default="None", max_length=255)),
                (
                    "product_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("quantity", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
