# Generated by Django 4.2 on 2023-04-24 02:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="product_name",
            field=models.CharField(default="None", max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="product_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
